### ISSUE TITLE
[install] KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/roundcube_ynh#49]
```
yunohost -v
yunohost: 
  repo: stable
  version: 3.3.4
yunohost-admin: 
  repo: stable
  version: 3.3.1
moulinette: 
  repo: stable
  version: 3.3.1
ssowat: 
  repo: stable
  version: 3.3.2
```
ynh on a vps 

hi, 
i tried to remove/reinstall roundcube, but reinstallation fails : 
https://paste.yunohost.org/raw/bimerunore

> 2019-01-22 11:48:31,117: WARNING -   Failed to execute git clone --mirror 'https://git.kolab.org/diffusion/PNL/php-net_ldap.git' '/var/www/roundcube/.composer/cache/vcs/https---git.kolab.org-diffusion-PNL-php-net-ldap.git/' 

thx for your help
